
# https://yarnpkg.com/configuration/yarnrc


#nodeLinker: "node-modules"

#.yarn/releases/yarn-3.0.2.cjs


#/*
#nodeLinker: pnp
#ignorePath: false
#cacheFolder: "./../../../../.yarn/cache"
#enableGlobalCache: true
#globalFolder: "./../../../../.yarn/global"
#yarnPath: "./../../../../.yarn/releases/yarn-3.0.2.cjs"
#*/

nodeLinker: pnp
ignorePath: false

enableGlobalCache: false
#cacheFolder: "/.yarn/cache"

#globalFolder: "./../../../../.yarn/global"
#yarnPath: "./../../../../.yarn/releases/yarn-3.0.2.cjs"
#deferredVersionFolder: "./../../../../.yarn/versions"
#pnpUnpluggedFolder: "./../../../../.yarn/unplugged"
